(function(g){var window=this;var UAa=function(a,b){return g.Vb(a,b)},Y5=function(a){g.Km(a,"zx",g.yb());
return a},Z5=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Nm(a.g,b,c)},VAa=function(a,b){var c=[];
g.sk(b,function(a){try{var b=g.dD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.cD(b)&&c.push(a):c.push(a)},a);
return c},WAa=function(a,b){var c=VAa(a,b);
(0,g.C)(c,function(a){g.dD.prototype.remove.call(this,a)},a)},XAa=function(a,b,c,d){var e=new g.Bm(null,void 0);
a&&g.Cm(e,a);b&&g.Dm(e,b);c&&g.Em(e,c);d&&g.Fm(e,d);return e},YAa=function(a){g.YF[a]&&(a=g.YF[a],(0,g.C)(a,function(a){g.WF[a]&&delete g.WF[a]}),a.length=0)},ZAa=function(a){var b=g.VF();
if(b)if(b.clear(a),a)YAa(a);else for(var c in g.YF)YAa(c)},$5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.vm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$Aa(this,a.capabilities||""),aBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},$Aa=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Ea(UAa,bBa)).forEach(function(b){a.capabilities.add(b)})},aBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},a6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},b6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},cBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},dBa=function(a){return new a6(a)},eBa=function(a){return g.ya(a)?(0,g.H)(a,dBa):[]},c6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},d6=function(a){return g.ya(a)?"["+(0,g.H)(a,c6).join(",")+"]":"null"},e6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},fBa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},f6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},g6=function(a,b){return g.Ma(a,function(a){return b6(a,b)})},gBa=function(){var a=(0,g.YG)();
a&&WAa(a,a.g.Md(!0))},h6=function(){var a=g.aH("yt-remote-connected-devices")||[];
g.gb(a);return a},hBa=function(a){if(g.Ra(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},iBa=function(a){g.$G("yt-remote-connected-devices",a,86400)},j6=function(){if(i6)return i6;
var a=g.aH("yt-remote-device-id");a||(a=e6(),g.$G("yt-remote-device-id",a,31536E3));for(var b=h6(),c=1,d=a;g.Qa(b,d);)c++,d=a+"#"+c;return i6=d},k6=function(){var a=h6(),b=j6();
g.Qa(a,b);g.cH()&&g.jb(a,b);a=hBa(a);if(g.Ra(a))try{g.IG("remote_sid")}catch(c){}else try{g.HG("remote_sid",a.join(","),-1)}catch(c){}},jBa=function(){return g.aH("yt-remote-session-browser-channel")},kBa=function(){return g.aH("yt-remote-local-screens")||[]},lBa=function(){g.$G("yt-remote-lounge-token-expiration",!0,86400)},mBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(kBa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.km)(c,function(a){return!g.Qa(b,a)})&&lBa();
g.$G("yt-remote-local-screens",a,31536E3)},nBa=function(a,b){g.$G("yt-remote-session-browser-channel",a);
g.$G("yt-remote-session-screen-id",b);var c=h6(),d=j6();g.Qa(c,d)||c.push(d);iBa(c);k6()},l6=function(a){a||(g.bH("yt-remote-session-screen-id"),g.bH("yt-remote-session-video-id"));
k6();a=h6();g.Va(a,j6());iBa(a)},oBa=function(){if(!m6){var a=g.oD();
a&&(m6=new g.YC(a))}return m6?!!m6.get("yt-remote-use-staging-server"):!1},pBa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Db(a)},qBa=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Zc(c,g.ce("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},rBa=function(){var a=pBa(),b=window.document.getElementById(a),c=b&&g.jF(b,"loaded");
c||b&&!c||(b=qBa(a,function(){g.jF(b,"loaded")||(g.iF(b,"loaded","true"),g.bG(a),g.XD(g.Ea(ZAa,a),0))}))},n6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},sBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},o6=function(a){a.length?tBa(a.shift(),function(){o6(a)}):p6()},uBa=function(a){return"chrome-extension://"+a+q6},tBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},r6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},p6=function(){var a=sBa();
a&&a(!1,"No cast extension found")},s6=function(){if(vBa){var a=2,b=sBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;tBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",p6,c)}},wBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(s6(),a({command:"cast.sender.init"}))},xBa=function(){s6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);o6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+q6,"//www.gstatic.com/eureka/clank"+q6])},t6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.ed=b;this.B=(0,g.z)(this.jI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},u6=function(){},v6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Rm(this);this.l=new g.tg;this.l.setInterval(250)},zBa=function(a,b,c){a.uj=1;
a.oh=Y5(b.clone());a.Ji=c;a.C=!0;yBa(a,null)},w6=function(a,b,c,d,e){a.uj=1;
a.oh=Y5(b.clone());a.Ji=null;a.C=c;e&&(a.zC=!1);yBa(a,d)},yBa=function(a,b){a.ak=(0,g.G)();
x6(a);a.Hh=a.oh.clone();Z5(a.Hh,"t",a.D);a.Wl=0;a.Rc=a.g.Hq(a.g.Ql()?b:null);0<a.mr&&(a.Xo=new g.Uk((0,g.z)(a.OD,a,a.Rc),a.mr));a.A.R(a.Rc,"readystatechange",a.nT);var c=a.li?g.cc(a.li):{};a.Ji?(a.Gp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Hh,a.Gp,a.Ji,c)):(a.Gp="GET",a.zC&&!g.xd&&(c.Connection="close"),a.Rc.send(a.Hh,a.Gp,null,c));a.g.rf(1)},CBa=function(a,b,c){for(var d=!0;!a.Uh&&a.Wl<c.length;){var e=ABa(a,c);
if(e==y6){4==b&&(a.ph=4,z6(15),d=!1);break}else if(e==BBa){a.ph=4;z6(16);d=!1;break}else A6(a,e)}4==b&&0==c.length&&(a.ph=1,z6(17),d=!1);a.wf=a.wf&&d;d||(B6(a),C6(a))},ABa=function(a,b){var c=a.Wl,d=b.indexOf("\n",c);
if(-1==d)return y6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return BBa;d+=1;if(d+c>b.length)return y6;var e=b.substr(d,c);a.Wl=d+c;return e},EBa=function(a,b){a.ak=(0,g.G)();
x6(a);var c=b?window.location.hostname:"";a.Hh=a.oh.clone();g.Km(a.Hh,"DOMAIN",c);g.Km(a.Hh,"t",a.D);try{a.xf=new window.ActiveXObject("htmlfile")}catch(n){B6(a);a.ph=7;z6(22);C6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in D6)k=D6[l];else if(l in DBa)k=D6[l]=DBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=D6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.$c(g.vc("b/12014412"),d);a.xf.open();a.xf.write(g.Sc(c));a.xf.close();a.xf.parentWindow.m=(0,g.z)(a.rS,a);a.xf.parentWindow.d=(0,g.z)(a.QB,a,!0);a.xf.parentWindow.rpcClose=(0,g.z)(a.QB,a,!1);c=a.xf.createElement("DIV");a.xf.parentWindow.document.body.appendChild(c);d=g.Hc(a.Hh.toString());d=g.qb(g.Ec(d));d=g.$c(g.vc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Sc(d);
a.g.rf(1)},x6=function(a){a.Yu=(0,g.G)()+a.B;
FBa(a,a.B)},FBa=function(a,b){if(null!=a.uk)throw Error("WatchDog timer not null");
a.uk=E6((0,g.z)(a.IS,a),b)},F6=function(a){a.uk&&(g.w.clearTimeout(a.uk),a.uk=null)},C6=function(a){a.g.Zx()||a.Uh||a.g.Ko(a)},B6=function(a){F6(a);
g.af(a.Xo);a.Xo=null;a.l.stop();g.Xm(a.A);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.xf&&(a.xf=null)},A6=function(a,b){try{a.g.JB(a,b),a.g.rf(4)}catch(c){}},HBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;GBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){HBa(a,b,c,d,f)},f)})}},GBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{G6(d),c(!0)}catch(e){}};
d.onerror=function(){try{G6(d),c(!1)}catch(e){}};
d.onabort=function(){try{G6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{G6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},G6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},IBa=function(a){this.g=a;
this.l=new u6},JBa=function(a){var b=H6(a.g,a.yk,"/mail/images/cleardot.gif");
Y5(b);HBa(b.toString(),5E3,(0,g.z)(a.vH,a),3,2E3);a.rf(1)},J6=function(a){var b=a.g.H;
if(null!=b)z6(5),b?(z6(11),I6(a.g,a,!1)):(z6(12),I6(a.g,a,!0));else if(a.te=new v6(a,void 0,void 0,void 0),a.te.li=a.jr,b=a.g,b=H6(b,b.Ql()?a.Vk:null,a.lr),z6(5),!g.vd||g.rc(10))Z5(b,"TYPE","xmlhttp"),w6(a.te,b,!1,a.Vk,!1);else{Z5(b,"TYPE","html");var c=a.te;a=!!a.Vk;c.uj=3;c.oh=Y5(b.clone());EBa(c,a)}},K6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new u6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},KBa=function(a,b){this.g=a;
this.map=b;this.context=null},LBa=function(a){g.cf.call(this,"statevent",a)},MBa=function(a,b){g.cf.call(this,"timingevent",a);
this.size=b},NBa=function(a){g.cf.call(this,"serverreachability",a)},QBa=function(a){OBa(a);
if(3==a.g){var b=a.Cl++,c=a.zn.clone();g.Km(c,"SID",a.o);g.Km(c,"RID",b);g.Km(c,"TYPE","terminate");L6(a,c);b=new v6(a,a.o,b,void 0);b.uj=2;b.oh=Y5(c.clone());(new window.Image).src=b.oh;b.ak=(0,g.G)();x6(b)}PBa(a)},RBa=function(a){a.QH(1,0);
a.zn=H6(a,null,a.ir);M6(a)},OBa=function(a){a.fh&&(a.fh.abort(),a.fh=null);
a.uc&&(a.uc.cancel(),a.uc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);N6(a);a.Rd&&(a.Rd.cancel(),a.Rd=null);a.hh&&(g.w.clearTimeout(a.hh),a.hh=null)},SBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new KBa(a.kO++,b));2!=a.g&&3!=a.g||M6(a)},M6=function(a){a.Rd||a.hh||(a.hh=E6((0,g.z)(a.OB,a),0),a.mj=0)},UBa=function(a,b){if(1==a.g){if(!b){a.Cl=Math.floor(1E5*Math.random());
var c=a.Cl++,d=new v6(a,"",c,void 0);d.li=null;var e=O6(a),f=a.zn.clone();g.Km(f,"RID",c);g.Km(f,"CVER","1");L6(a,f);zBa(d,f,e);a.Rd=d;a.g=2}}else 3==a.g&&(b?TBa(a,b):0==a.l.length||a.Rd||TBa(a))},TBa=function(a,b){if(b)if(6<a.Wh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Cl-1;var d=O6(a)}else c=b.F,d=b.Ji;else c=a.Cl++,d=O6(a);var e=a.zn.clone();g.Km(e,"SID",a.o);g.Km(e,"RID",c);g.Km(e,"AID",a.Jj);L6(a,e);c=new v6(a,a.o,c,a.mj+1);c.li=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Rd=c;zBa(c,e,d)},L6=function(a,b){if(a.rd){var c=a.rd.Hx();
c&&g.Mb(c,function(a,c){g.Km(b,c,a)})}},O6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Wh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Wh?e:f-d;try{g.Mb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},VBa=function(a){a.uc||a.pg||(a.D=1,a.pg=E6((0,g.z)(a.NB,a),0),a.bj=0)},P6=function(a){if(a.uc||a.pg||3<=a.bj)return!1;
a.D++;a.pg=E6((0,g.z)(a.NB,a),WBa(a,a.bj));a.bj++;return!0},I6=function(a,b,c){a.Fp=c;
a.If=b.xg;a.C||RBa(a)},N6=function(a){null!=a.Yh&&(g.w.clearTimeout(a.Yh),a.Yh=null)},WBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Q6=function(a,b){if(2==b||9==b){var c=null;
a.rd&&(c=null);var d=(0,g.z)(a.iU,a);c||(c=new g.Bm("//www.google.com/images/cleardot.gif"),Y5(c));GBa(c.toString(),1E4,d)}else z6(2);XBa(a,b)},XBa=function(a,b){a.g=0;
a.rd&&a.rd.Bw(b);PBa(a);OBa(a)},PBa=function(a){a.g=0;
a.If=-1;if(a.rd)if(0==a.A.length&&0==a.l.length)a.rd.wq();else{g.Ya(a.A);var b=g.Ya(a.l);a.A.length=0;a.l.length=0;a.rd.wq(b)}},H6=function(a,b,c){var d=g.Lm(c);
if(""!=d.l)b&&g.Dm(d,b+"."+d.l),g.Em(d,d.B);else{var e=window.location;d=XAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ik&&g.Mb(a.Ik,function(a,b){g.Km(d,b,a)});
g.Km(d,"VER",a.Wh);L6(a,d);return d},E6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},z6=function(a){R6.dispatchEvent(new LBa(R6,a))},YBa=function(){},ZBa=function(a,b){this.action=a;
this.params=b||{}},S6=function(a,b){g.K.call(this);
this.g=new g.du(this.iS,0,this);g.L(this,this.g);this.ed=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},T6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.XC;this.l=new S6(this.NU,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},$Ba=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Fp,sessionId:a.g.o,arrayId:a.g.Jj}},aCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&UBa(a.g),QBa(a.g));a.F=0},U6=function(a){return!!a.g&&3==a.g.g},bCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},V6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Ng(a)||"";b&&(this.port=":"+b);this.domain=g.Mg(a)||"";a=g.Kb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cb(a,"10.0")&&(this.l=!1))},W6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Wg(c+b,{})},X6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Gb:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),wd:g.Ea(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uE(b,a)},fCa=function(){var a=cCa;
dCa();Y6.push(a);eCa(Y6)},Z6=function(a,b){dCa();
var c=Y6,d=gCa(a,String(b));g.Ra(c)?hCa(d):(eCa(c),(0,g.C)(c,function(a){a(d)}))},dCa=function(){Y6||(Y6=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",Y6,void 0))},hCa=function(a){var b=($6+1)%50;
$6=b;a7[b]=a;b7||(b7=49==b)},eCa=function(a){var b=a7;
if(b[0]){var c=$6,d=b7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
a7=Array(50);$6=-1;b7=!1}},gCa=function(a,b){var c=((0,g.G)()-iCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},c7=function(a){g.OF.call(this);
this.D=a;this.g=[]},jCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},kCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!f6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=jCa(a,b[d])||c;return c},lCa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},d7=function(a,b,c,d){g.OF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},f7=function(a){c7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;e7(this);this.info("Initializing with "+d6(this.g))},mCa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=W6(a.o,"/pairing/get_lounge_token_batch");
X6(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.vI,a),(0,g.z)(a.uI,a))}},e7=function(a){var b=eBa(kBa());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return kCa(a,b)},g7=function(a,b){mBa((0,g.H)(a.g,cBa));
b&&lBa()},i7=function(a,b){g.OF.call(this);
this.C=b;var c=g.aH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Qa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;h7("Initialized with "+g.Dg(this.g))},nCa=function(a,b,c){var d=W6(a.B,"/pairing/get_screen_availability");
X6(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},j7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(h7("Updated online screens: "+g.Dg(a.g)),a.g=b,a.P("screenChange"));oCa(a)},k7=function(a){(0,window.isNaN)(a.o)||g.ZD(a.o);
a.o=g.XD((0,g.z)(a.iu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},h7=function(a){Z6("OnlineScreenService",a)},pCa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},oCa=function(a){a=g.Sb(g.Nb(a.g,function(a){return a}));
g.gb(a);a.length?g.$G("yt-remote-online-screen-ids",a.join(","),60):g.bH("yt-remote-online-screen-ids")},l7=function(a){c7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};qCa(this)},sCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ne();if(k=(c?g6(k,c):null)||g6(k,b)){k.uuid=b;var l=m7(a,k);nCa(a.l,l,function(a){e(a?l:null)})}else c?rCa(a,c,(0,g.z)(function(a){var f=m7(this,new a6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));nCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},tCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},rCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Gb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.uE(W6(a.C,"/pairing/get_lounge_token_batch"),e)},uCa=function(a){a.g=a.o.ne();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+d6(a.g))},qCa=function(a){n7(a);
a.o=new f7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.LI,a));uCa(a);a.A=eBa(g.aH("yt-remote-automatic-screen-cache")||[]);n7(a);a.info("Initializing automatic screens: "+d6(a.A));a.l=new i7(a.C,(0,g.z)(a.ne,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},m7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=g6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.$G("yt-remote-automatic-screen-cache",(0,g.H)(a.A,cBa)));n7(a);a.B[b.uuid]=b.id;g.$G("yt-remote-device-id-map",a.B,31536E3);return b},n7=function(a){a.B=g.aH("yt-remote-device-id-map")||{}},o7=function(a,b,c){g.OF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},p7=function(a,b){Z6(a.M,b)},q7=function(a,b){o7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.TU,this);this.B=(0,g.z)(this.SS,this);this.A=g.XD((0,g.z)(function(){vCa(this,null)},this),12E4)},wCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Dg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){p7(this,"Failed to send message: getMdxSessionStatus.")},a)):p7(a,"Sending yt message without session: "+g.Dg(b))},vCa=function(a,b){g.ZD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Lo,a),d=(0,g.z)(a.re,a);a.Sx(b,c,d,5)}}else a.re(Error("Waiting for session status timed out."))},r7=function(a,b,c){o7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.WU,this);this.g=g.y},xCa=function(a){a.g=a.H.VD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Lo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.re(a)},a))},yCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}oBa()&&(b.env_useStageMdx=1);return g.Ug(b)},s7=function(a,b){o7.call(this,a,b,"ManualSession");
this.g=g.XD((0,g.z)(this.Kj,this,null),150)},t7=function(a,b,c,d){g.OF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.wR,this)},zCa=function(a,b){return b?g.Ma(a.o,function(a){return b6(b,a.label)},a):null},u7=function(a){Z6("Controller",a)},cCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},v7=function(a){return a.B||!!a.o.length||!!a.g},w7=function(a,b,c){b!=a.g&&(g.af(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.LB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Kj(null)):a.P("yt-remote-cast2-session-change",null))},ACa=function(a){var b=a.l.UD(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&b6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=zCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},GCa=function(a,b,c,d,e,f,k){BCa()?CCa(b,e,f,k)&&(y7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?DCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?DCa(a,c):(z7("Failed to load cast API: "+d),A7(!1),y7(!1),g.bH("yt-remote-cast-available"),g.bH("yt-remote-cast-receiver"),ECa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):rBa():r6("CriOS")?wBa():r6("Android")&&r6("Chrome/")&&window.navigator.presentation?xBa():window.chrome&&window.navigator.presentation&&!r6("Edge")?(s6(),o6(FCa.map(uBa))):p6())):x7("Cannot initialize because not running Chrome")},ECa=function(){x7("dispose");
var a=B7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);HCa(!1);g.$F(C7);C7.length=0},D7=function(){return!!g.aH("yt-remote-cast-installed")},ICa=function(){var a=g.aH("yt-remote-cast-receiver");
return a?a.friendlyName:null},JCa=function(){x7("clearCurrentReceiver");
g.bH("yt-remote-cast-receiver")},KCa=function(){return D7()?B7()?B7().getCastSession():(z7("getCastSelector: Cast is not initialized."),null):(z7("getCastSelector: Cast API is not installed!"),null)},F7=function(){D7()?B7()?E7()?(x7("Requesting cast selector."),B7().requestSession()):(x7("Wait for cast API to be ready to request the session."),C7.push(g.ZF("yt-remote-cast2-api-ready",F7))):z7("requestCastSelector: Cast is not initialized."):z7("requestCastSelector: Cast API is not installed!")},G7=
function(a,b){E7()?B7().setConnectedScreenStatus(a,b):z7("setConnectedScreenStatus called before ready.")},BCa=function(){var a=0<=g.Kb.search(/ (CrMo|Chrome|CriOS)\//);
return g.bK||a},LCa=function(a,b){B7().init(a,b)},CCa=function(a,b,c,d){var e=!1;
B7()||(a=new t7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.$G("yt-remote-cast-available",a);g.cG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){x7("onReceiverSelected: "+a.friendlyName);
g.$G("yt-remote-cast-receiver",a);g.cG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){x7("onReceiverResumed: "+a.friendlyName);
g.$G("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){x7("onSessionChange: "+c6(a));
a||g.bH("yt-remote-cast-receiver");g.cG("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
x7("cloudview.createSingleton_: "+e);return e},B7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},DCa=function(a,b){A7(!0);
y7(!1);LCa(a,function(a){a?(HCa(!0),g.bG("yt-remote-cast2-api-ready")):(z7("Failed to initialize cast API."),A7(!1),g.bH("yt-remote-cast-available"),g.bH("yt-remote-cast-receiver"),ECa());b(a)})},x7=function(a){Z6("cloudview",a)},z7=function(a){Z6("cloudview",a)},A7=function(a){x7("setCastInstalled_ "+a);
g.$G("yt-remote-cast-installed",a)},E7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},HCa=function(a){x7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},y7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},H7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Lf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},I7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},J7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},K7=function(a,b){a.F=b;
a.D=(0,g.G)()},L7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},M7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&I7(a)},N7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.l);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},P7=function(a,b){g.OF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.nC;this.o=this.l=null;this.H=(0,g.z)(this.TO,this);this.D=(0,g.z)(this.Fl,this);this.F=(0,g.z)(this.SO,this);this.I=(0,g.z)(this.gP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ev,this),MCa(this))):c=3;0!=c&&(b?this.ev(c):g.XD((0,g.z)(function(){this.ev(c)},this),0));
var d=KCa();d&&O7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},Q7=function(a){return new H7(a.A.getPlayerContextData())},MCa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.sR,a),this))},a)},NCa=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},R7=function(a,b){50>a.B.Dc()&&g.pC(a.B,b)},T7=function(a,b,c){var d=Q7(a);
K7(d,c);-1E3!=d.g&&(d.g=b);S7(a,d)},U7=function(a,b,c){a.A.sendMessage(b,c)},S7=function(a,b){NCa(a);
a.A.setPlayerContextData(N7(b));MCa(a)},O7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Fl(null));
a.o=b;a.o&&(Z6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Fl(a.o.media[0]))},OCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=Q7(a);b.contentId!=d.videoId&&Z6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;K7(d,a.l.getEstimatedTime());S7(a,d)}else Z6("CP","No cast media video. Ignoring state update.")},V7=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),U7(this,b,c))},a)},W7=function(a,b,c){g.OF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.V=[];this.A=this.D=this.o=this.Za=this.g=null;this.ma=a;this.V.push(g.yF(window,"beforeunload",(0,g.z)(this.mI,this)));this.l=[];this.Za=new H7;this.X=b.id;this.g=PCa(this,c);this.g.subscribe("handlerOpened",this.XO,this);this.g.subscribe("handlerClosed",this.UO,this);this.g.subscribe("handlerError",this.VO,this);this.g.subscribe("handlerMessage",this.WO,this);bCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.cH()&&g.$G("yt-remote-session-video-id",a)},this)},X7=function(a){Z6("conn",a)},PCa=function(a,b){return new T6(W6(a.ma,"/bc"),b)},Y7=function(a,b){a.P("proxyStateChange",b)},QCa=function(a){a.B=g.XD((0,g.z)(function(){X7("Connecting timeout");
this.C(1)},a),2E4)},Z7=function(a){g.ZD(a.B);
a.B=window.NaN},$7=function(a){g.ZD(a.M);
a.M=window.NaN},RCa=function(a){a8(a);
a.K=g.XD((0,g.z)(function(){b8(this,"getNowPlaying")},a),2E4)},a8=function(a){g.ZD(a.K);
a.K=window.NaN},TCa=function(a,b){b&&(Z7(a),$7(a));
b==(U6(a.g)&&(0,window.isNaN)(a.B))?b&&(Y7(a,1),b8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),Y7(a,1),b8(a,"getNowPlaying"),SCa(a)):a.C(1)},UCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Yb(b.params)?a.Za.l=null:a.Za.l=b.params,a.P("remotePlayerChange"))},VCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;M7(a.Za,c,d);a.P("remoteQueueChange")},XCa=function(a,b){b.params=b.params||{};
VCa(a,b);WCa(a,b);a.P("autoplayDismissed")},WCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
K7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?RCa(a):a8(a);
a.P("remotePlayerChange")},YCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);K7(a.Za,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},ZCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.P("remotePlayerChange")},$Ca=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},aDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Lf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.P("previousNextChange")},SCa=function(a){g.ZD(a.I);
a.I=g.XD((0,g.z)(a.C,a,1),864E5)},b8=function(a,b,c){c?X7("Sending: action="+b+", params="+g.Dg(c)):X7("Sending: action="+b);
a.g.sendMessage(b,c)},c8=function(a){c7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.RU,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.TQ,this)))},fDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.RD("MDX_CONFIG")||b;gBa();k6();d8||(d8=new V6(b?b.loungeApiHost:void 0),oBa()&&(d8.g="/api/loungedev"));e8||(e8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",e8,void 0));bDa();var c=f8();if(!c){var d=new l7(d8);g.va("yt.mdx.remote.screenService_",d,void 0);c=f8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);GCa(a,d,function(a){a?g8()&&G7(g8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.cG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),h8("Initializing: "+g.Dg(b)),i8.push(g.ZF("yt-remote-cast2-availability-change",function(){g.cG("yt-remote-receiver-availability-change")})),i8.push(g.ZF("yt-remote-cast2-receiver-selected",function(){j8(null);
g.cG("yt-remote-auto-connect","cast-selector-receiver")})),i8.push(g.ZF("yt-remote-cast2-receiver-resumed",function(){g.cG("yt-remote-receiver-resumed","cast-selector-receiver")})),i8.push(g.ZF("yt-remote-cast2-session-change",cDa)),i8.push(g.ZF("yt-remote-connection-change",function(a){a?G7(g8(),"YouTube TV"):k8()||(G7(null,null),JCa())})),a=l8(),b.isAuto&&(a.id+="#dial"),g.PE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),h8(" -- with channel params: "+
g.Dg(a)),dDa(a),c.start(),g8()||eDa())},hDa=function(){var a=gDa();
D7()&&g.aH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},gDa=function(){var a=f8().dd.$_gos();
var b=m8();b&&n8()&&(f6(a,b)||a.push(b));return fBa(a)},o8=function(){var a=iDa();
!a&&D7()&&ICa()&&(a={key:"cast-selector-receiver",name:ICa()});return a},iDa=function(){var a=gDa(),b=m8();
b||(b=k8());return g.Ma(a,function(a){return b&&b6(b,a.key)?!0:!1})},m8=function(){var a=g8();
if(!a)return null;var b=f8().ne();return g6(b,a)},cDa=function(a){h8("remote.onCastSessionChange_: "+c6(a));
if(a){var b=m8();b&&b.id==a.id?G7(b.id,"YouTube TV"):(b&&p8(),q8(a,1))}else n8()&&p8()},p8=function(){E7()?B7().stopSession():z7("stopSession called before API ready.");
var a=n8();a&&(a.disconnect(1),r8(null))},s8=function(){var a=n8();
return!!a&&3!=a.getProxyState()},h8=function(a){Z6("remote",a)},f8=function(){if(!t8){var a=g.x("yt.mdx.remote.screenService_");
t8=a?new c8(a):null}return t8},g8=function(){return g.x("yt.mdx.remote.currentScreenId_")},jDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},kDa=function(){return g.x("yt.mdx.remote.connectData_")},j8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},n8=function(){return g.x("yt.mdx.remote.connection_")},r8=function(a){var b=n8();
j8(null);a||jDa("");g.va("yt.mdx.remote.connection_",a,void 0);e8&&((0,g.C)(e8,function(b){b(a)}),e8.length=0);
b&&!a?g.cG("yt-remote-connection-change",!1):!b&&a&&g.cG("yt-remote-connection-change",!0)},k8=function(){var a=g.cH();
if(!a)return null;var b=f8().ne();return g6(b,a)},q8=function(a,b){m8()&&m8();
jDa(a.id);var c=new W7(d8,a,l8());c.connect(b,kDa());c.subscribe("beforeDisconnect",function(a){g.cG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){n8()&&r8(null)});
r8(c)},eDa=function(){var a=k8();
a?(h8("Resume connection to: "+c6(a)),q8(a,0)):(l6(),JCa(),h8("Skipping connecting because no session screen found."))},bDa=function(){var a=l8();
if(g.Yb(a)){a=j6();var b=g.aH("yt-remote-session-name")||"",c=g.aH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},l8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},dDa=function(a){a?(g.$G("yt-remote-session-app",a.app),g.$G("yt-remote-session-name",a.name)):(g.bH("yt-remote-session-app"),g.bH("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},u8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.LF(this);g.L(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.lQ);this.o.O(b,"captionschanged",this.RO);this.o.O(b,"captionssettingschanged",this.dD);this.o.O(b,"videoplayerreset",this.Mo);this.o.O(b,"mdxautoplaycancel",this.uH);this.V=this.o.O(b,"onVolumeChange",this.vB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.IB,this);c.subscribe("remotePlayerChange",this.Il,this);c.subscribe("remoteQueueChange",this.Mo,this);c.subscribe("autoplayUpNext",this.dB,
this);c.subscribe("previousNextChange",this.FB,this);c.subscribe("nowAutoplaying",this.xB,this);c.subscribe("autoplayDismissed",this.cB,this);this.suggestion=null;this.H=new g.hP(64);this.A=new g.du(this.ZC,500,this);g.L(this,this.A);this.B=new g.du(this.aD,1E3,this);g.L(this,this.B);this.K=new t6(this.uU,0,this);g.L(this,this.K);this.C={};this.M=new g.du(this.GD,1E3,this);g.L(this,this.M);this.I=new g.Uk(this.XM,1E3,this);g.L(this,this.I);this.N=g.y;this.dD();this.Mo();this.Il()},v8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},lDa=function(a){v8(a,0);
a.A.stop();w8(a,new g.hP(64))},y8=function(a,b){if(x8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ci()},g.fc(c,b));a.g.RC(a.l.ea(1).videoId,c);a.C=Q7(a.g).l}},z8=function(a,b){var c=a.l.Wf();
if(c){var d=c.je();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Fj;var m=Q7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};M7(m,k,l);g.t(b)&&(K7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);U7(c,"setPlaylist",q);e||S7(c,m);w8(a,new g.hP(1))},mDa=function(a,b){if(b){var c=a.l.zc("captions","tracklist",{Oy:1});
c&&c.length?(a.l.Jd("captions","track",b),a.D=!1):(a.l.tl("captions"),a.D=!0)}else a.l.Jd("captions","track",{})},x8=function(a){return Q7(a.g).videoId==a.l.ea(1).videoId},w8=function(a,b){a.B.stop();
var c=a.H;if(!g.pP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.ZU(a.l,d);a.H=b;nDa(a.F,c,b)}},A8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.woa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.EV(this,250);g.L(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);oDa(this,g.WU(a))},oDa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.zc("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},B8=function(a,b){g.GZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},C8=function(a){g.tV.call(this,a);
g.eH({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:e6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.hP(64);this.H=0;if(!g.OM(g.Y(this.g))){a=
this.g;var b=g.vI(a);b&&(b=b.to())&&(b=new B8(a,b),g.L(this,b));b=new A8(a);g.L(this,b);g.nV(a,b.element,4)}},nDa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.vP(c,b))},D8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)p8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Wf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.kc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Fj,index:Math.max(a.g.Mz(),0),currentTime:0==f?void 0:f}}else c=null;h8("Connecting to: "+g.Dg(b));"cast-selector-receiver"==b.key?(j8(c||null),E7()?B7().setLaunchParams(c||null):z7("setLaunchParams called before ready.")):!c&&
s8()&&g8()==b.key?g.cG("yt-remote-connection-change",!0):(p8(),j8(c||null),c=f8().ne(),(c=g6(c,b.key))&&q8(c,1))}},DBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},D6={"'":"\\'"},pDa={},bBa={iW:"atp",H0:"ska",W_:"que",f_:"mus",D0:"sus"};
$5.prototype.fn=function(){var a=new $5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var m6,i6="",q6=n6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",vBa=n6("loadCastFramework")||n6("loadCastApplicationFramework"),FCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(t6,g.K);g.h=t6.prototype;g.h.iI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.ed:this.xa=g.ug(this.B,this.ed)};
g.h.stop=function(){this.xa&&(g.vg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();t6.Z.U.call(this)};
g.h.jI=function(){this.o?(this.xa=g.ug(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};u6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
u6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=v6.prototype;g.h.li=null;g.h.wf=!1;g.h.uk=null;g.h.Yu=null;g.h.ak=null;g.h.uj=null;g.h.oh=null;g.h.Hh=null;g.h.Ji=null;g.h.Rc=null;g.h.Wl=0;g.h.xf=null;g.h.Gp=null;g.h.ph=null;g.h.Wk=-1;g.h.zC=!0;g.h.Uh=!1;g.h.mr=0;g.h.Xo=null;var BBa={},y6={};g.h=v6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.nT=function(a){a=a.target;var b=this.Xo;b&&3==g.rx(a)?b.sj():this.OD(a)};
g.h.OD=function(a){try{if(a==this.Rc)a:{var b=g.rx(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.vd&&!g.rc(10)||g.xd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.ef&&!g.vx(this.Rc))break a;this.Uh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));F6(this);var e=this.Rc.getStatus();this.Wk=e;var f=g.vx(this.Rc);(this.wf=200==e)?(4==b&&B6(this),this.C?(CBa(this,b,f),g.ef&&this.wf&&3==b&&(this.A.R(this.l,"tick",this.gT),this.l.start())):A6(this,f),this.wf&&!this.Uh&&(4==b?this.g.Ko(this):
(this.wf=!1,x6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ph=3,z6(13)):(this.ph=0,z6(14)),B6(this),C6(this))}}catch(k){this.Rc&&g.vx(this.Rc)}finally{}};
g.h.gT=function(){var a=g.rx(this.Rc),b=g.vx(this.Rc);this.Wl<b.length&&(F6(this),CBa(this,a,b),this.wf&&4!=a&&x6(this))};
g.h.rS=function(a){E6((0,g.z)(this.qS,this,a),0)};
g.h.qS=function(a){this.Uh||(F6(this),A6(this,a),x6(this))};
g.h.QB=function(a){E6((0,g.z)(this.pS,this,a),0)};
g.h.pS=function(a){this.Uh||(B6(this),this.wf=a,this.g.Ko(this),this.g.rf(4))};
g.h.cancel=function(){this.Uh=!0;B6(this)};
g.h.IS=function(){this.uk=null;var a=(0,g.G)();0<=a-this.Yu?(2!=this.uj&&this.g.rf(3),B6(this),this.ph=2,z6(18),C6(this)):FBa(this,this.Yu-a)};g.h=IBa.prototype;g.h.jr=null;g.h.te=null;g.h.Yo=!1;g.h.ay=null;g.h.wn=null;g.h.kr=null;g.h.lr=null;g.h.Le=null;g.h.xg=-1;g.h.Vk=null;g.h.yk=null;g.h.connect=function(a){this.lr=a;a=H6(this.g,null,this.lr);z6(3);this.ay=(0,g.G)();var b=this.g.F;null!=b?(this.Vk=b[0],(this.yk=b[1])?(this.Le=1,JBa(this)):(this.Le=2,J6(this))):(Z5(a,"MODE","init"),this.te=new v6(this,void 0,void 0,void 0),this.te.li=this.jr,w6(this.te,a,!1,null,!0),this.Le=0)};
g.h.vH=function(a){if(a)this.Le=2,J6(this);else{z6(4);var b=this.g;b.If=b.fh.xg;Q6(b,9)}a&&this.rf(2)};
g.h.Hq=function(a){return this.g.Hq(a)};
g.h.abort=function(){this.te&&(this.te.cancel(),this.te=null);this.xg=-1};
g.h.Zx=function(){return!1};
g.h.JB=function(a,b){this.xg=a.Wk;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.If=this.xg;Q6(c,2);return}this.Vk=c[0];this.yk=c[1]}else c=this.g,c.If=this.xg,Q6(c,2);else if(2==this.Le)if(this.Yo)z6(7),this.kr=(0,g.G)();else if("11111"==b){if(z6(6),this.Yo=!0,this.wn=(0,g.G)(),c=this.wn-this.ay,!g.vd||g.rc(10)||500>c)this.xg=200,this.te.cancel(),z6(12),I6(this.g,this,!0)}else z6(8),this.wn=this.kr=(0,g.G)(),this.Yo=!1};
g.h.Ko=function(){this.xg=this.te.Wk;if(this.te.wf)0==this.Le?this.yk?(this.Le=1,JBa(this)):(this.Le=2,J6(this)):2==this.Le&&((!g.vd||g.rc(10)?!this.Yo:200>this.kr-this.wn)?(z6(11),I6(this.g,this,!1)):(z6(12),I6(this.g,this,!0)));else{0==this.Le?z6(9):2==this.Le&&z6(10);var a=this.g;a.If=this.xg;Q6(a,2)}};
g.h.Ql=function(){return this.g.Ql()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=K6.prototype;g.h.Ik=null;g.h.Rd=null;g.h.uc=null;g.h.ir=null;g.h.zn=null;g.h.qw=null;g.h.On=null;g.h.Cl=0;g.h.kO=0;g.h.rd=null;g.h.hh=null;g.h.pg=null;g.h.Yh=null;g.h.fh=null;g.h.Fp=null;g.h.Jj=-1;g.h.Zy=-1;g.h.If=-1;g.h.mj=0;g.h.bj=0;g.h.Wh=8;var R6=new g.Ff;g.A(LBa,g.cf);g.A(MBa,g.cf);g.A(NBa,g.cf);g.h=K6.prototype;g.h.connect=function(a,b,c,d,e){z6(0);this.ir=b;this.Ik=c||{};d&&g.t(e)&&(this.Ik.OSID=d,this.Ik.OAID=e);this.C?(E6((0,g.z)(this.Ow,this,a),100),RBa(this)):this.Ow(a)};
g.h.Ow=function(a){this.fh=new IBa(this);this.fh.jr=null;this.fh.l=this.B;this.fh.connect(a)};
g.h.Zx=function(){return 0==this.g};
g.h.OB=function(a){this.hh=null;UBa(this,a)};
g.h.NB=function(){this.pg=null;this.uc=new v6(this,this.o,"rpc",this.D);this.uc.li=null;this.uc.mr=0;var a=this.qw.clone();g.Km(a,"RID","rpc");g.Km(a,"SID",this.o);g.Km(a,"CI",this.Fp?"0":"1");g.Km(a,"AID",this.Jj);L6(this,a);if(!g.vd||g.rc(10))g.Km(a,"TYPE","xmlhttp"),w6(this.uc,a,!0,this.On,!1);else{g.Km(a,"TYPE","html");var b=this.uc,c=!!this.On;b.uj=3;b.oh=Y5(a.clone());EBa(b,c)}};
g.h.JB=function(a,b){if(0!=this.g&&(this.uc==a||this.Rd==a))if(this.If=a.Wk,this.Rd==a&&3==this.g)if(7<this.Wh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.uc)if(this.uc.ak+3E3<this.Rd.ak)N6(this),this.uc.cancel(),this.uc=null;else break a;P6(this);z6(19)}}else this.Zy=c[1],0<this.Zy-this.Jj&&37500>c[2]&&this.Fp&&0==this.bj&&!this.Yh&&(this.Yh=E6((0,g.z)(this.MO,this),6E3));else Q6(this,11)}else b!=pDa.pX.g&&Q6(this,11);else if(this.uc==a&&
N6(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Jj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.On=e[2],e=e[3],null!=e?this.Wh=e:this.Wh=6,this.g=3,this.rd&&this.rd.Dw(),this.qw=H6(this,this.Ql()?this.On:null,this.ir),VBa(this)):"stop"==e[0]&&Q6(this,7):3==this.g&&("stop"==e[0]?Q6(this,7):"noop"!=e[0]&&this.rd&&this.rd.Cw(e),this.bj=0)}}};
g.h.MO=function(){null!=this.Yh&&(this.Yh=null,this.uc.cancel(),this.uc=null,P6(this),z6(20))};
g.h.Ko=function(a){if(this.uc==a){N6(this);this.uc=null;var b=2}else if(this.Rd==a)this.Rd=null,b=1;else return;this.If=a.Wk;if(0!=this.g)if(a.wf)1==b?(b=(0,g.G)()-a.ak,R6.dispatchEvent(new MBa(R6,a.Ji?a.Ji.length:0,b,this.mj)),M6(this),this.A.length=0):VBa(this);else{var c=a.ph,d;if(!(d=3==c||7==c||0==c&&0<this.If)){if(d=1==b)this.Rd||this.hh||1==this.g||2<=this.mj?d=!1:(this.hh=E6((0,g.z)(this.OB,this,a),WBa(this,this.mj)),this.mj++,d=!0);d=!(d||2==b&&P6(this))}if(d)switch(c){case 1:Q6(this,5);
break;case 4:Q6(this,10);break;case 3:Q6(this,6);break;case 7:Q6(this,12);break;default:Q6(this,2)}}};
g.h.QH=function(a){if(!g.Qa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.iU=function(a){a?z6(2):(z6(1),XBa(this,8))};
g.h.Hq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.hx;a.F=!1;return a};
g.h.isActive=function(){return!!this.rd&&this.rd.isActive(this)};
g.h.rf=function(a){R6.dispatchEvent(new NBa(R6,a))};
g.h.Ql=function(){return!(!g.vd||g.rc(10))};
g.h=YBa.prototype;g.h.Dw=function(){};
g.h.Cw=function(){};
g.h.Bw=function(){};
g.h.wq=function(){};
g.h.Hx=function(){return{}};
g.h.isActive=function(){return!0};g.A(S6,g.K);g.h=S6.prototype;g.h.iS=function(){this.ed=Math.min(3E5,2*this.ed);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.ed+15E3*Math.random();g.eu(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.ed=5E3};g.A(T6,YBa);g.h=T6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Ld=function(a){return this.o.Ld(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.af(this.o),aCa(this),g.af(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new K6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.rd=null);d.rd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Jj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):U6(this)&&SBa(this.g,c)};
g.h.Dw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)SBa(this.g,a[b])}this.P("handlerOpened")};
g.h.Bw=function(a){var b=2==a&&401==this.g.If;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.wq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Hx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.fc(a,this.B);return a};
g.h.Cw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),QBa(this.g)):this.P("handlerMessage",new ZBa(a[0],a[1]))};
g.h.NU=function(){this.l.isActive();var a=this.g,b=0;a.uc&&b++;a.Rd&&b++;0!=b||this.connect(this.B,this.A)};V6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
V6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
V6.prototype.B=function(a){a(Error("request timed out"))};var iCa=(0,g.G)(),Y6=null,a7=Array(50),$6=-1,b7=!1;g.A(c7,g.OF);c7.prototype.ne=function(){return this.g};
c7.prototype.contains=function(a){return!!f6(this.g,a)};
c7.prototype.get=function(a){return a?g6(this.g,a):null};
c7.prototype.info=function(a){Z6(this.D,a)};g.A(d7,g.OF);var qDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=d7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.TD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.ZD(this.xa),this.xa=window.NaN)};
g.h.U=function(){this.stop();d7.Z.U.call(this)};
g.h.TD=function(){this.xa=window.NaN;this.g=g.uE(W6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Gb:(0,g.z)(this.PU,this),onError:(0,g.z)(this.OU,this),wd:(0,g.z)(this.QU,this)})};
g.h.PU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new a6(c))};
g.h.OU=function(a){this.g=null;a.status&&404==a.status?this.l>=qDa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=qDa[this.l],this.xa=g.XD((0,g.z)(this.TD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.QU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(f7,c7);g.h=f7.prototype;g.h.start=function(){e7(this)&&this.P("screenChange");!g.aH("yt-remote-lounge-token-expiration")&&mCa(this);g.ZD(this.l);this.l=g.XD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){e7(this);jCa(this,a);g7(this,!1);this.P("screenChange");b(a);a.token||mCa(this)};
g.h.remove=function(a,b){var c=e7(this);lCa(this,a)&&(g7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Bp=function(a,b,c,d){var e=e7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,g7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.ZD(this.l);f7.Z.U.call(this)};
g.h.vI=function(a){e7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}g7(this,!b);b&&Z6(this.D,"Missed "+b+" lounge tokens.")};
g.h.uI=function(a){Z6(this.D,"Requesting lounge tokens failed: "+a)};g.A(i7,g.OF);g.h=i7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.aH("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?k7(this):(this.A=(0,g.G)()+3E5,g.$G("yt-remote-fast-check-period",this.A),this.iu())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){h7("Updating availability on schedule.");var a=this.C(),b=g.Nb(this.g,function(b,d){return b&&!!g6(a,d)},this);
j7(this,b)};
g.h.U=function(){g.ZD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);i7.Z.U.call(this)};
g.h.iu=function(){g.ZD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=pCa(this);if(g.Qb(a)){var b=W6(this.B,"/pairing/get_screen_availability");this.l=X6(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.QR,this,a),(0,g.z)(this.PR,this))}else j7(this,{}),k7(this)};
g.h.QR=function(a,b){this.l=null;var c=g.Sb(pCa(this));if(g.ib(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;j7(this,d);k7(this)}else this.gc("Changing Screen set during request."),this.iu()};
g.h.PR=function(a){this.gc("Screen availability failed: "+a);this.l=null;k7(this)};
g.h.gc=function(a){Z6("OnlineScreenService",a)};g.A(l7,c7);g.h=l7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Bp=function(a,b,c,d){this.o.contains(a)?this.o.Bp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Z6(this.D,a),d(Error(a)))};
g.h.ne=function(a){return a?this.g:g.Xa(this.g,(0,g.Jd)(this.A,function(a){return!this.contains(a)},this))};
g.h.UD=function(){return(0,g.Jd)(this.ne(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.VD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new d7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.af(f);d(m7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.af(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.SU=function(a,b,c,d){g.uE(W6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Gb:(0,g.z)(function(a,d){var e=new a6(d.screen||{});if(!e.name||tCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);tCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(m7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.af(this.o);g.af(this.l);l7.Z.U.call(this)};
g.h.LI=function(){uCa(this);this.P("screenChange");this.l.update()};
l7.prototype.dispose=l7.prototype.dispose;g.A(o7,g.OF);g.h=o7.prototype;g.h.Lo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.re=function(a){this.ha()||(a&&p7(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){Z6(this.M,a)};
g.h.XD=function(){return null};
g.h.ru=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){p7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.ru("");o7.Z.U.call(this)};g.A(q7,o7);g.h=q7.prototype;g.h.qu=function(a){if(this.g){if(this.g==a)return;p7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);wCa(this)};
g.h.Kj=function(a){this.info("launchWithParams no-op for Cast: "+g.Dg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.re()},this),(0,g.z)(function(){this.re(Error("Failed to stop receiver app."))},this)):this.re(Error("Stopping cast device witout session."))};
g.h.ru=g.y;g.h.U=function(){this.info("disposeInternal");g.ZD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;q7.Z.U.call(this)};
g.h.SS=function(a,b){if(!this.ha())if(b){var c=g.bx(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Dg(c));switch(d){case "mdxSessionStatus":vCa(this,c.screenId);break;default:p7(this,"Unknown youtube message: "+d)}}else p7(this,"Unable to parse message.")}else p7(this,"No data in message.")};
g.h.Sx=function(a,b,c,d){sCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(p7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.XD((0,g.z)(this.Sx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.XD=function(){return this.g};
g.h.TU=function(a){this.ha()||a||(p7(this,"Cast session died."),this.re())};g.A(r7,o7);g.h=r7.prototype;g.h.qu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Kj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.ZD(this.C);this.A?this.A.stop((0,g.z)(this.re,this,null),(0,g.z)(this.re,this,"Failed to stop DIAL device.")):this.re()};
g.h.U=function(){this.g();this.g=g.y;g.ZD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;r7.Z.U.call(this)};
g.h.WU=function(a){this.ha()||a||(p7(this,"DIAL session died."),this.g(),this.g=g.y,this.re())};
g.h.Vr=function(a){this.I=e6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,yCa(this));a(b);xCa(this)}else this.D=(0,g.z)(function(){g.ZD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,yCa(this));a(b);xCa(this)},this),this.C=g.XD((0,g.z)(function(){this.D()},this),100)};
g.h.bK=function(a,b,c){sCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Lo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Vr(b,c)},this),(0,g.z)(function(a){p7(this,"Failed to get DIAL screen: "+a);
this.Vr(b,c)},this))};g.A(s7,o7);s7.prototype.stop=function(){this.re()};
s7.prototype.qu=g.y;s7.prototype.Kj=function(){g.ZD(this.g);this.g=window.NaN;var a=g6(this.H.ne(),this.l.label);a?this.Lo(a):this.re(Error("No such screen"))};
s7.prototype.U=function(){g.ZD(this.g);this.g=window.NaN;s7.Z.U.call(this)};g.A(t7,g.OF);g.h=t7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.KB,this),(0,g.z)(this.AR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.xP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),fCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.WD,this)),this.o=ACa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.Dg(a))},this)),this.P("yt-remote-cast2-availability-change",v7(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.Dg(a));
b(!1)},this))};
g.h.PT=function(a,b){u7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)u7("Unsetting old screen status: "+this.g.l.friendlyName),w7(this,null)}if(a&&b){if(!this.g){c=g6(this.l.ne(),a);if(!c){u7("setConnectedScreenStatus: Unknown screen.");return}var d=zCa(this,c);d||(u7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.Dg(a))},this)));
u7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);w7(this,new s7(this.l,d),!0)}this.g.ru(b)}else u7("setConnectedScreenStatus: no screen.")};
g.h.QT=function(a){this.ha()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Kj(a):this.gc("Setting connection data without a session")};
g.h.VU=function(){this.ha()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),w7(this,null)):u7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.KB,this),(0,g.z)(this.VR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.WD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Va(g.x("yt.mdx.remote.debug.handlers_")||[],cCa);g.af(this.g);t7.Z.U.call(this)};
g.h.gc=function(a){Z6("Controller",a)};
g.h.LB=function(a,b){this.g==a&&(b||w7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.wR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),u7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)u7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{u7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:w7(this,
new s7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:w7(this,new r7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:w7(this,new q7(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.xP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return u7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);w7(this,new r7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.bK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Vr,b))};
g.h.KB=function(a){if(!this.ha()){u7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)u7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),w7(this,new q7(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=g6(this.l.ne(),c.label);
d&&b6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(u7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.af(this.g),this.g=new q7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.LB,this,this.g)),this.g.Kj(null));this.g.qu(a)}}};
g.h.UU=function(){return this.g?this.g.XD():null};
g.h.VR=function(a){this.ha()||(this.gc("Failed to estabilish a session: "+g.Dg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&w7(this,null))};
g.h.AR=function(a){u7("Receiver availability updated: "+a);if(!this.ha()){var b=v7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;v7(this)!=b&&this.P("yt-remote-cast2-availability-change",v7(this))}};
g.h.WD=function(){this.ha()||(this.o=ACa(this),u7("Updating custom receivers: "+g.Dg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",v7(this)))};
t7.prototype.setLaunchParams=t7.prototype.QT;t7.prototype.setConnectedScreenStatus=t7.prototype.PT;t7.prototype.stopSession=t7.prototype.VU;t7.prototype.getCastSession=t7.prototype.UU;t7.prototype.requestSession=t7.prototype.requestSession;t7.prototype.init=t7.prototype.init;t7.prototype.dispose=t7.prototype.dispose;var C7=[];g.h=H7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";I7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+J7(this):this.H};
g.h.clone=function(){return new H7(N7(this))};g.A(P7,g.OF);g.h=P7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,V7(this,"play")):U7(this,"play"),T7(this,1,L7(Q7(this))),this.P("remotePlayerChange")):R7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,V7(this,"pause")):U7(this,"pause"),T7(this,2,L7(Q7(this))),this.P("remotePlayerChange")):R7(this,this.pause)};
g.h.SD=function(a){if(1==this.g){if(this.l){var b=Q7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,V7(this,"seekTo",{newTime:a}))}else U7(this,"seekTo",{newTime:a});T7(this,3,a);this.P("remotePlayerChange")}else R7(this,g.Ea(this.SD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,V7(this,"stopVideo")):U7(this,"stopVideo");var a=Q7(this);a.index=-1;a.videoId="";I7(a);S7(this,a);this.P("remotePlayerChange")}else R7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=Q7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){Z6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){Z6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);U7(this,"setVolume",e)}c.muted=b;c.volume=a;S7(this,c)}else R7(this,g.Ea(this.setVolume,a,b))};
g.h.RC=function(a,b){if(1==this.g){var c=Q7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Dg(b.style),g.fc(d,c.l));U7(this,"setSubtitlesTrack",d);S7(this,c)}else R7(this,g.Ea(this.RC,a,b))};
g.h.dv=function(a,b){if(1==this.g){U7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=Q7(this);c.audioTrackId=b.Pb.id;S7(this,c)}else R7(this,g.Ea(this.dv,a,b))};
g.h.RD=function(a,b){if(1==this.g){if(a&&b){var c=Q7(this);M7(c,a,b);S7(this,c)}U7(this,"previous")}else R7(this,g.Ea(this.RD,a,b))};
g.h.QD=function(a,b){if(1==this.g){if(a&&b){var c=Q7(this);M7(c,a,b);S7(this,c)}U7(this,"next")}else R7(this,g.Ea(this.QD,a,b))};
g.h.jx=function(){1==this.g?U7(this,"dismissAutoplay"):R7(this,this.jx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}P7.Z.dispose.call(this)};
g.h.U=function(){NCa(this);this.A=null;this.B.clear();O7(this,null);P7.Z.U.call(this)};
g.h.ev=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.qC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.sR=function(a,b){this.P(a,b)};
g.h.TO=function(a){if(!a)this.Fl(null),O7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=Q7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,S7(this,b)}};
g.h.Fl=function(a){Z6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),OCa(this),this.P("remotePlayerChange")};
g.h.SO=function(a){a?(OCa(this),this.P("remotePlayerChange")):this.Fl(null)};
g.h.gP=function(){var a=KCa();a&&O7(this,a)};
g.h.gc=function(a){Z6("CP",a)};g.A(W7,g.OF);g.h=W7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;K7(this.Za,m);this.A="UNSUPPORTED";X7("Connecting with setPlaylist and params: "+g.Dg(l));this.g.connect({method:"setPlaylist",params:g.Dg(l)},a,jBa())}else X7("Connecting without params"),
this.g.connect({},a,jBa());QCa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),Y7(this,3));W7.Z.dispose.call(this)};
g.h.U=function(){Z7(this);a8(this);$7(this);g.ZD(this.H);this.H=window.NaN;g.ZD(this.I);this.I=window.NaN;this.o=null;g.zF(this.V);this.V.length=0;this.g.dispose();W7.Z.U.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.mI=function(){this.C(2)};
g.h.XO=function(){X7("Channel opened");this.N&&(this.N=!1,$7(this),this.M=g.XD((0,g.z)(function(){X7("Timing out waiting for a screen.");this.C(1)},this),15E3));
nBa($Ba(this.g),this.X)};
g.h.UO=function(){X7("Channel closed");(0,window.isNaN)(this.B)?l6(!0):l6();this.dispose()};
g.h.VO=function(a){l6();(0,window.isNaN)(this.F())?(X7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,X7("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Y7(this,2))};
g.h.WO=function(a){a.params?X7("Received: action="+a.action+", params="+g.Dg(a.params)):X7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.bx(a.params.devices);this.l=(0,g.H)(a,function(a){return new $5(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
TCa(this,a);break;case "loungeScreenDisconnected":g.Wa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
TCa(this,!1);break;case "remoteConnected":var b=new $5(g.bx(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Ta(this.l,b);
break;case "remoteDisconnected":b=new $5(g.bx(a.params.device));g.Wa(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":VCa(this,a);break;case "nowPlaying":XCa(this,a);break;case "onStateChange":WCa(this,a);break;case "onAdStateChange":YCa(this,a);break;case "onVolumeChanged":ZCa(this,a);break;case "onSubtitlesTrackChanged":UCa(this,a);break;case "nowAutoplaying":$Ca(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":aDa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:X7("Unrecognized action: "+a.action)}};
g.h.zT=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&b8(this,"getNowPlaying")}};
W7.prototype.subscribe=W7.prototype.subscribe;W7.prototype.unsubscribeByKey=W7.prototype.Ld;W7.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?U6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
W7.prototype.getProxyState=W7.prototype.da;W7.prototype.C=function(a){X7("Disconnecting with "+a);Z7(this);this.P("beforeDisconnect",a);1==a&&l6();aCa(this.g,a);this.dispose()};
W7.prototype.disconnect=W7.prototype.C;W7.prototype.ca=function(){var a=this.Za;this.o&&(a=this.Za.clone(),M7(a,this.o,a.index));return N7(a)};
W7.prototype.getPlayerContextData=W7.prototype.ca;
W7.prototype.ka=function(a){var b=new H7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.ZD(this.H),this.H=g.XD((0,g.z)(this.zT,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&L7(this.Za)==L7(b)&&g.Dg(this.Za.l)==g.Dg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
W7.prototype.setPlayerContextData=W7.prototype.ka;W7.prototype.W=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
W7.prototype.getOtherConnectedRemoteId=W7.prototype.W;W7.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
W7.prototype.getReconnectTimeout=W7.prototype.F;W7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
W7.prototype.getAutoplayMode=W7.prototype.Y;W7.prototype.ba=function(){return this.D||""};
W7.prototype.getAutoplayVideoId=W7.prototype.ba;W7.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.fu(a.g);a.start()}};
W7.prototype.reconnect=W7.prototype.oa;W7.prototype.fa=function(a,b){b8(this,a,b);SCa(this)};
W7.prototype.sendMessage=W7.prototype.fa;g.A(c8,c7);g.h=c8.prototype;g.h.ne=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Bp=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;c8.Z.U.call(this)};
g.h.RU=function(){this.P("screenChange")};
g.h.TQ=function(){this.P("onlineScreenChange")};
l7.prototype.$_st=l7.prototype.start;l7.prototype.$_gspc=l7.prototype.SU;l7.prototype.$_gsppc=l7.prototype.VD;l7.prototype.$_c=l7.prototype.contains;l7.prototype.$_g=l7.prototype.get;l7.prototype.$_a=l7.prototype.add;l7.prototype.$_un=l7.prototype.Bp;l7.prototype.$_r=l7.prototype.remove;l7.prototype.$_gs=l7.prototype.ne;l7.prototype.$_gos=l7.prototype.UD;l7.prototype.$_s=l7.prototype.subscribe;l7.prototype.$_ubk=l7.prototype.Ld;var d8=null,e8=null,t8=null,i8=[];g.p(u8,g.K);g.h=u8.prototype;
g.h.U=function(){g.K.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.IB,this);this.g.unsubscribe("remotePlayerChange",this.Il,this);this.g.unsubscribe("remoteQueueChange",this.Mo,this);this.g.unsubscribe("autoplayUpNext",this.dB,this);this.g.unsubscribe("previousNextChange",this.FB,this);this.g.unsubscribe("nowAutoplaying",this.xB,this);this.g.unsubscribe("autoplayDismissed",this.cB,this);this.g=this.F=null};
g.h.iA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(x8(this)){if(!Q7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":Q7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.sj(c[0],c[1]);break;case "control_subtitles_set_track":y8(this,c[0]);break;case "control_set_audio_track":c=c[0],x8(this)&&this.g.dv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();z8(this,0==c?void 0:c);break;case "control_seek":z8(this,c[0]);break;case "control_subtitles_set_track":y8(this,c[0]);break;case "control_set_audio_track":c=c[0],x8(this)&&this.g.dv(this.l.ea(1).videoId,c)}};
g.h.RO=function(a){this.K.iI(a)};
g.h.uU=function(a){this.iA("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.dD=function(){var a=this.l.zc("captions","track");g.Yb(a)||y8(this,a)};
g.h.vB=function(a){if(x8(this)){this.g.unsubscribe("remotePlayerChange",this.Il,this);var b=Math.round(a.volume);a=!!a.muted;var c=Q7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Il,this)}};
g.h.lQ=function(){g.Yb(this.C)||mDa(this,this.C);this.D=!1};
g.h.IB=function(a,b){this.B.stop();2==b&&this.aD()};
g.h.Il=function(){if(x8(this)){this.A.stop();var a=Q7(this.g);switch(a.g){case 1081:case 1:w8(this,new g.hP(8));this.ZC();break;case 1085:case 3:w8(this,new g.hP(9));break;case 1083:case 0:w8(this,new g.hP(2));this.I.stop();v8(this,this.l.ea().lengthSeconds);break;case 1084:w8(this,new g.hP(4));break;case 2:w8(this,new g.hP(4));v8(this,L7(a));break;case -1:w8(this,new g.hP(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},w8(this,new g.hP(128,a))}a=Q7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,mDa(this,a));a=Q7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.GD()}else lDa(this)};
g.h.FB=function(){this.l.P("mdxpreviousnextchange")};
g.h.Mo=function(){x8(this)||lDa(this)};
g.h.uH=function(){this.g.jx()};
g.h.dB=function(a){a&&(a=g.uE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Gb:(0,g.z)(this.uS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.uS=function(a,b){var c=new g.iO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.xB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.cB=function(){this.l.P("mdxautoplaycanceled")};
g.h.XM=function(a,b){-1==Q7(this.g).g?z8(this,a):b&&this.g.SD(a)};
g.h.GD=function(){if(x8(this)){var a=Q7(this.g);this.o.Ba(this.V);a.muted?this.l.mute():this.l.Xf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.vB)}};
g.h.ZC=function(){this.A.stop();if(!this.g.ha()){var a=Q7(this.g);a.kb()&&w8(this,new g.hP(8));v8(this,L7(a));this.A.start()}};
g.h.aD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(A8,g.W);A8.prototype.A=function(a){oDa(this,a.state)};g.p(B8,g.GZ);B8.prototype.I=function(){var a=this.l.zc("remote","receivers");a&&1<a.length&&!this.l.zc("remote","quickCast")?(this.F=g.kb(a,this.B,this),g.HZ(this,(0,g.H)(a,this.B)),a=this.l.zc("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
B8.prototype.B=function(a){return a.key};
B8.prototype.pf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
B8.prototype.ud=function(a){g.GZ.prototype.ud.call(this,a);this.l.Jd("remote","currentReceiver",this.F[a]);this.A.Qb()};g.p(C8,g.tV);g.h=C8.prototype;g.h.create=function(){fDa(g.CM(g.Y(this.g)));this.C.push(g.ZF("yt-remote-before-disconnect",this.NO,this));this.C.push(g.ZF("yt-remote-connection-change",this.CR,this));this.C.push(g.ZF("yt-remote-receiver-availability-change",this.GB,this));this.C.push(g.ZF("yt-remote-auto-connect",this.zR,this));this.C.push(g.ZF("yt-remote-receiver-resumed",this.yR,this));this.GB()};
g.h.load=function(){this.g.Ws();g.tV.prototype.load.call(this);this.B=new u8(this,this.g,this.l);var a=(a=kDa())?a.currentTime:0;var b=s8()?new P7(n8(),void 0):null;0==a&&b&&(a=L7(Q7(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));nDa(this,this.D,this.D);g.R_(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.bf(this.B,this.l);this.l=this.B=null;g.tV.prototype.unload.call(this);g.R_(this.g.app,5)};
g.h.U=function(){g.$F(this.C);g.tV.prototype.U.call(this)};
g.h.xl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.iA.apply(this.B,[].concat([a],g.qa(c)))};
g.h.eI=function(){return this.loaded?this.B.suggestion:null};
g.h.Lf=function(){return this.l?Q7(this.l).Lf:!1};
g.h.hasNext=function(){return this.l?Q7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.LM=function(){var a=Q7(this.l),b=this.g.ea();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+J7(a):a.A,isPeggedToLive:1>=(a.C?a.o+J7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+J7(a):a.o,seekableStart:0<a.B?a.B+J7(a):a.B}};
g.h.MM=function(){this.l&&this.l.QD()};
g.h.NM=function(){this.l&&this.l.RD()};
g.h.NO=function(a){1==a&&(this.I=this.l?Q7(this.l):null)};
g.h.CR=function(){var a=s8()?new P7(n8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.af(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Kz(a.videoId,L7(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.GB=function(){this.F=[this.o].concat(hDa());var a=o8()||this.o;D8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.zR=function(){var a=o8();D8(this,a)};
g.h.yR=function(){this.A=o8()};
g.h.KM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?F7():D8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&F7(),!0):!1}};
g.h.OM=function(){U7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qc=function(){return!1};g.bY.remote=C8;})(_yt_player);
